/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PublicHealthRouteImport } from './routes/public-health'
import { Route as MapRouteImport } from './routes/map'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGemmaSummarizeVoiceRouteImport } from './routes/api/gemma.summarize-voice'
import { Route as ApiGemmaAnalyzeImageRouteImport } from './routes/api/gemma.analyze-image'
import { Route as ApiBackboardSessionRouteImport } from './routes/api/backboard.session'

const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicHealthRoute = PublicHealthRouteImport.update({
  id: '/public-health',
  path: '/public-health',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGemmaSummarizeVoiceRoute = ApiGemmaSummarizeVoiceRouteImport.update({
  id: '/api/gemma/summarize-voice',
  path: '/api/gemma/summarize-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGemmaAnalyzeImageRoute = ApiGemmaAnalyzeImageRouteImport.update({
  id: '/api/gemma/analyze-image',
  path: '/api/gemma/analyze-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackboardSessionRoute = ApiBackboardSessionRouteImport.update({
  id: '/api/backboard/session',
  path: '/api/backboard/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/doctor': typeof DoctorRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/public-health': typeof PublicHealthRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/api/backboard/session': typeof ApiBackboardSessionRoute
  '/api/gemma/analyze-image': typeof ApiGemmaAnalyzeImageRoute
  '/api/gemma/summarize-voice': typeof ApiGemmaSummarizeVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/doctor': typeof DoctorRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/public-health': typeof PublicHealthRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/api/backboard/session': typeof ApiBackboardSessionRoute
  '/api/gemma/analyze-image': typeof ApiGemmaAnalyzeImageRoute
  '/api/gemma/summarize-voice': typeof ApiGemmaSummarizeVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkin': typeof CheckinRoute
  '/doctor': typeof DoctorRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/public-health': typeof PublicHealthRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/api/backboard/session': typeof ApiBackboardSessionRoute
  '/api/gemma/analyze-image': typeof ApiGemmaAnalyzeImageRoute
  '/api/gemma/summarize-voice': typeof ApiGemmaSummarizeVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkin'
    | '/doctor'
    | '/insights'
    | '/map'
    | '/public-health'
    | '/report'
    | '/rewards'
    | '/api/backboard/session'
    | '/api/gemma/analyze-image'
    | '/api/gemma/summarize-voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkin'
    | '/doctor'
    | '/insights'
    | '/map'
    | '/public-health'
    | '/report'
    | '/rewards'
    | '/api/backboard/session'
    | '/api/gemma/analyze-image'
    | '/api/gemma/summarize-voice'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkin'
    | '/doctor'
    | '/insights'
    | '/map'
    | '/public-health'
    | '/report'
    | '/rewards'
    | '/api/backboard/session'
    | '/api/gemma/analyze-image'
    | '/api/gemma/summarize-voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckinRoute: typeof CheckinRoute
  DoctorRoute: typeof DoctorRoute
  InsightsRoute: typeof InsightsRoute
  MapRoute: typeof MapRoute
  PublicHealthRoute: typeof PublicHealthRoute
  ReportRoute: typeof ReportRoute
  RewardsRoute: typeof RewardsRoute
  ApiBackboardSessionRoute: typeof ApiBackboardSessionRoute
  ApiGemmaAnalyzeImageRoute: typeof ApiGemmaAnalyzeImageRoute
  ApiGemmaSummarizeVoiceRoute: typeof ApiGemmaSummarizeVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-health': {
      id: '/public-health'
      path: '/public-health'
      fullPath: '/public-health'
      preLoaderRoute: typeof PublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemma/summarize-voice': {
      id: '/api/gemma/summarize-voice'
      path: '/api/gemma/summarize-voice'
      fullPath: '/api/gemma/summarize-voice'
      preLoaderRoute: typeof ApiGemmaSummarizeVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemma/analyze-image': {
      id: '/api/gemma/analyze-image'
      path: '/api/gemma/analyze-image'
      fullPath: '/api/gemma/analyze-image'
      preLoaderRoute: typeof ApiGemmaAnalyzeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backboard/session': {
      id: '/api/backboard/session'
      path: '/api/backboard/session'
      fullPath: '/api/backboard/session'
      preLoaderRoute: typeof ApiBackboardSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckinRoute: CheckinRoute,
  DoctorRoute: DoctorRoute,
  InsightsRoute: InsightsRoute,
  MapRoute: MapRoute,
  PublicHealthRoute: PublicHealthRoute,
  ReportRoute: ReportRoute,
  RewardsRoute: RewardsRoute,
  ApiBackboardSessionRoute: ApiBackboardSessionRoute,
  ApiGemmaAnalyzeImageRoute: ApiGemmaAnalyzeImageRoute,
  ApiGemmaSummarizeVoiceRoute: ApiGemmaSummarizeVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
