/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyReportRouteImport } from './routes/weekly-report'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PublicHealthRouteImport } from './routes/public-health'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AlexaRouteImport } from './routes/alexa'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiCheckinsRouteImport } from './routes/api/checkins'
import { Route as ApiAlexaRouteImport } from './routes/api/alexa'
import { Route as ApiGemmaTriageRouteImport } from './routes/api/gemma.triage'
import { Route as ApiGemmaSummarizeVoiceRouteImport } from './routes/api/gemma.summarize-voice'
import { Route as ApiGemmaAnalyzeImageRouteImport } from './routes/api/gemma.analyze-image'
import { Route as ApiBackboardSessionRouteImport } from './routes/api/backboard.session'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth.signup'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth.session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin.users'
import { Route as ApiAdminPendingAccountsRouteImport } from './routes/api/admin.pending-accounts'
import { Route as ApiAdminApproveAccountRouteImport } from './routes/api/admin.approve-account'

const WeeklyReportRoute = WeeklyReportRouteImport.update({
  id: '/weekly-report',
  path: '/weekly-report',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicHealthRoute = PublicHealthRouteImport.update({
  id: '/public-health',
  path: '/public-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlexaRoute = AlexaRouteImport.update({
  id: '/alexa',
  path: '/alexa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckinsRoute = ApiCheckinsRouteImport.update({
  id: '/api/checkins',
  path: '/api/checkins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlexaRoute = ApiAlexaRouteImport.update({
  id: '/api/alexa',
  path: '/api/alexa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGemmaTriageRoute = ApiGemmaTriageRouteImport.update({
  id: '/api/gemma/triage',
  path: '/api/gemma/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGemmaSummarizeVoiceRoute = ApiGemmaSummarizeVoiceRouteImport.update({
  id: '/api/gemma/summarize-voice',
  path: '/api/gemma/summarize-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGemmaAnalyzeImageRoute = ApiGemmaAnalyzeImageRouteImport.update({
  id: '/api/gemma/analyze-image',
  path: '/api/gemma/analyze-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackboardSessionRoute = ApiBackboardSessionRouteImport.update({
  id: '/api/backboard/session',
  path: '/api/backboard/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPendingAccountsRoute = ApiAdminPendingAccountsRouteImport.update({
  id: '/api/admin/pending-accounts',
  path: '/api/admin/pending-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApproveAccountRoute = ApiAdminApproveAccountRouteImport.update({
  id: '/api/admin/approve-account',
  path: '/api/admin/approve-account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alexa': typeof AlexaRoute
  '/checkin': typeof CheckinRoute
  '/doctor': typeof DoctorRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/public-health': typeof PublicHealthRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/weekly-report': typeof WeeklyReportRoute
  '/api/alexa': typeof ApiAlexaRoute
  '/api/checkins': typeof ApiCheckinsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/admin/approve-account': typeof ApiAdminApproveAccountRoute
  '/api/admin/pending-accounts': typeof ApiAdminPendingAccountsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/backboard/session': typeof ApiBackboardSessionRoute
  '/api/gemma/analyze-image': typeof ApiGemmaAnalyzeImageRoute
  '/api/gemma/summarize-voice': typeof ApiGemmaSummarizeVoiceRoute
  '/api/gemma/triage': typeof ApiGemmaTriageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alexa': typeof AlexaRoute
  '/checkin': typeof CheckinRoute
  '/doctor': typeof DoctorRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/public-health': typeof PublicHealthRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/weekly-report': typeof WeeklyReportRoute
  '/api/alexa': typeof ApiAlexaRoute
  '/api/checkins': typeof ApiCheckinsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/admin/approve-account': typeof ApiAdminApproveAccountRoute
  '/api/admin/pending-accounts': typeof ApiAdminPendingAccountsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/backboard/session': typeof ApiBackboardSessionRoute
  '/api/gemma/analyze-image': typeof ApiGemmaAnalyzeImageRoute
  '/api/gemma/summarize-voice': typeof ApiGemmaSummarizeVoiceRoute
  '/api/gemma/triage': typeof ApiGemmaTriageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alexa': typeof AlexaRoute
  '/checkin': typeof CheckinRoute
  '/doctor': typeof DoctorRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/public-health': typeof PublicHealthRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/weekly-report': typeof WeeklyReportRoute
  '/api/alexa': typeof ApiAlexaRoute
  '/api/checkins': typeof ApiCheckinsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/admin/approve-account': typeof ApiAdminApproveAccountRoute
  '/api/admin/pending-accounts': typeof ApiAdminPendingAccountsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/backboard/session': typeof ApiBackboardSessionRoute
  '/api/gemma/analyze-image': typeof ApiGemmaAnalyzeImageRoute
  '/api/gemma/summarize-voice': typeof ApiGemmaSummarizeVoiceRoute
  '/api/gemma/triage': typeof ApiGemmaTriageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alexa'
    | '/checkin'
    | '/doctor'
    | '/insights'
    | '/map'
    | '/profile'
    | '/public-health'
    | '/report'
    | '/rewards'
    | '/weekly-report'
    | '/api/alexa'
    | '/api/checkins'
    | '/api/profile'
    | '/api/admin/approve-account'
    | '/api/admin/pending-accounts'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/signup'
    | '/api/backboard/session'
    | '/api/gemma/analyze-image'
    | '/api/gemma/summarize-voice'
    | '/api/gemma/triage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alexa'
    | '/checkin'
    | '/doctor'
    | '/insights'
    | '/map'
    | '/profile'
    | '/public-health'
    | '/report'
    | '/rewards'
    | '/weekly-report'
    | '/api/alexa'
    | '/api/checkins'
    | '/api/profile'
    | '/api/admin/approve-account'
    | '/api/admin/pending-accounts'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/signup'
    | '/api/backboard/session'
    | '/api/gemma/analyze-image'
    | '/api/gemma/summarize-voice'
    | '/api/gemma/triage'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alexa'
    | '/checkin'
    | '/doctor'
    | '/insights'
    | '/map'
    | '/profile'
    | '/public-health'
    | '/report'
    | '/rewards'
    | '/weekly-report'
    | '/api/alexa'
    | '/api/checkins'
    | '/api/profile'
    | '/api/admin/approve-account'
    | '/api/admin/pending-accounts'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/signup'
    | '/api/backboard/session'
    | '/api/gemma/analyze-image'
    | '/api/gemma/summarize-voice'
    | '/api/gemma/triage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlexaRoute: typeof AlexaRoute
  CheckinRoute: typeof CheckinRoute
  DoctorRoute: typeof DoctorRoute
  InsightsRoute: typeof InsightsRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  PublicHealthRoute: typeof PublicHealthRoute
  ReportRoute: typeof ReportRoute
  RewardsRoute: typeof RewardsRoute
  WeeklyReportRoute: typeof WeeklyReportRoute
  ApiAlexaRoute: typeof ApiAlexaRoute
  ApiCheckinsRoute: typeof ApiCheckinsRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiAdminApproveAccountRoute: typeof ApiAdminApproveAccountRoute
  ApiAdminPendingAccountsRoute: typeof ApiAdminPendingAccountsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiBackboardSessionRoute: typeof ApiBackboardSessionRoute
  ApiGemmaAnalyzeImageRoute: typeof ApiGemmaAnalyzeImageRoute
  ApiGemmaSummarizeVoiceRoute: typeof ApiGemmaSummarizeVoiceRoute
  ApiGemmaTriageRoute: typeof ApiGemmaTriageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-report': {
      id: '/weekly-report'
      path: '/weekly-report'
      fullPath: '/weekly-report'
      preLoaderRoute: typeof WeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-health': {
      id: '/public-health'
      path: '/public-health'
      fullPath: '/public-health'
      preLoaderRoute: typeof PublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alexa': {
      id: '/alexa'
      path: '/alexa'
      fullPath: '/alexa'
      preLoaderRoute: typeof AlexaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkins': {
      id: '/api/checkins'
      path: '/api/checkins'
      fullPath: '/api/checkins'
      preLoaderRoute: typeof ApiCheckinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alexa': {
      id: '/api/alexa'
      path: '/api/alexa'
      fullPath: '/api/alexa'
      preLoaderRoute: typeof ApiAlexaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemma/triage': {
      id: '/api/gemma/triage'
      path: '/api/gemma/triage'
      fullPath: '/api/gemma/triage'
      preLoaderRoute: typeof ApiGemmaTriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemma/summarize-voice': {
      id: '/api/gemma/summarize-voice'
      path: '/api/gemma/summarize-voice'
      fullPath: '/api/gemma/summarize-voice'
      preLoaderRoute: typeof ApiGemmaSummarizeVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemma/analyze-image': {
      id: '/api/gemma/analyze-image'
      path: '/api/gemma/analyze-image'
      fullPath: '/api/gemma/analyze-image'
      preLoaderRoute: typeof ApiGemmaAnalyzeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backboard/session': {
      id: '/api/backboard/session'
      path: '/api/backboard/session'
      fullPath: '/api/backboard/session'
      preLoaderRoute: typeof ApiBackboardSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pending-accounts': {
      id: '/api/admin/pending-accounts'
      path: '/api/admin/pending-accounts'
      fullPath: '/api/admin/pending-accounts'
      preLoaderRoute: typeof ApiAdminPendingAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approve-account': {
      id: '/api/admin/approve-account'
      path: '/api/admin/approve-account'
      fullPath: '/api/admin/approve-account'
      preLoaderRoute: typeof ApiAdminApproveAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlexaRoute: AlexaRoute,
  CheckinRoute: CheckinRoute,
  DoctorRoute: DoctorRoute,
  InsightsRoute: InsightsRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  PublicHealthRoute: PublicHealthRoute,
  ReportRoute: ReportRoute,
  RewardsRoute: RewardsRoute,
  WeeklyReportRoute: WeeklyReportRoute,
  ApiAlexaRoute: ApiAlexaRoute,
  ApiCheckinsRoute: ApiCheckinsRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiAdminApproveAccountRoute: ApiAdminApproveAccountRoute,
  ApiAdminPendingAccountsRoute: ApiAdminPendingAccountsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiBackboardSessionRoute: ApiBackboardSessionRoute,
  ApiGemmaAnalyzeImageRoute: ApiGemmaAnalyzeImageRoute,
  ApiGemmaSummarizeVoiceRoute: ApiGemmaSummarizeVoiceRoute,
  ApiGemmaTriageRoute: ApiGemmaTriageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
